version: '3.4'

networks:
  cargowhalenetwork: {}

volumes:
  cargowhale_sql: {}
  azurite: {}

services:
  cargowhale:
    image: ${DOCKER_REGISTRY-}cargowhale
    networks:
      - cargowhalenetwork
    build:
      context: .
      dockerfile: Application/Cargowhale/Dockerfile
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /sample/config.json:/config.json

  cargowhale.sql:
    image: mcr.microsoft.com/mssql/server:2019-latest
    networks:
      - cargowhalenetwork
    ports:
      - "1433:1433"
    environment:
      ACCEPT_EULA: "Y"
      SA_PASSWORD: "^dEbX2Ew"
    volumes:
      - cargowhale_sql:/var/opt/mssql
      - ./Docker/Databases/Sql:/scripts
    restart: unless-stopped
    command:
      - "/scripts/init.sh"

  # Azurite currently does not support file upload, see https://github.com/microsoft/mssql-docker/issues/721
  #localazurite.blob.core.windows.net:
  #  image: mcr.microsoft.com/azure-storage/azurite:3.14.0
  #  networks:
  #    - cargowhalenetwork
  #  ports:
  #    - "10000:10000"
  #    - "10001:10001"
  #    - "10002:10002"
  #  entrypoint: "azurite --loose -l /data --oauth=basic --cert=/azuriteDir/certs/azuriteCert.crt --key=/azuriteDir/certs/azuriteKey.pem --blobPort 10000 --blobHost 0.0.0.0 --queuePort 10001 --queueHost 0.0.0.0 --tablePort 10002 --tableHost 0.0.0.0"
  #  labels:
  #    - ideamachinecompose
  #  volumes:
  #    - azurite:/data
  #    - ./Azurite:/azuriteDir